#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : docopt
Version  : 0.6.2
Release  : 3
URL      : https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Summary  : Command line arguments parser for C++11 and later
Group    : Development/Tools
License  : MIT
Requires: docopt-license = %{version}-%{release}
Requires: docopt-python = %{version}-%{release}
Requires: docopt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
``docopt`` creates *beautiful* command-line interfaces
======================================================================

%package license
Summary: license components for the docopt package.
Group: Default

%description license
license components for the docopt package.


%package python
Summary: python components for the docopt package.
Group: Default
Requires: docopt-python3 = %{version}-%{release}

%description python
python components for the docopt package.


%package python3
Summary: python3 components for the docopt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the docopt package.


%prep
%setup -q -n docopt-0.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551109375
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/docopt
cp LICENSE-MIT %{buildroot}/usr/share/package-licenses/docopt/LICENSE-MIT
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/docopt/LICENSE-MIT

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
